
{
    "login": "ELAndrews",
    "id": 54676884,
    "node_id": "MDQ6VXNlcjU0Njc2ODg0",
    "avatar_url": "https://avatars1.githubusercontent.com/u/54676884?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/ELAndrews",
    "html_url": "https://github.com/ELAndrews",
    "followers_url": "https://api.github.com/users/ELAndrews/followers",
    "following_url": "https://api.github.com/users/ELAndrews/following{/other_user}",
    "gists_url": "https://api.github.com/users/ELAndrews/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/ELAndrews/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/ELAndrews/subscriptions",
    "organizations_url": "https://api.github.com/users/ELAndrews/orgs",
    "repos_url": "https://api.github.com/users/ELAndrews/repos",
    "events_url": "https://api.github.com/users/ELAndrews/events{/privacy}",
    "received_events_url": "https://api.github.com/users/ELAndrews/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Emma Andrews",
    "company": null,
    "blog": "",
    "location": null,
    "email": null,
    "hireable": null,
    "bio": null,
    "public_repos": 34,
    "public_gists": 0,
    "followers": 10,
    "following": 9,
    "created_at": "2019-08-29T14:52:09Z",
    "updated_at": "2019-12-03T12:22:14Z"
  }